name: modl_env
channels:
  - conda-forge
  - defaults
dependencies:
  #   conda install pytorch=2.0.1 torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
  #   result in : pytorch=2.0.1, pytorch-cuda=11.7, pytorch-mutex=1.0, python=3.10.12
  
  # - libcufile=1.7.2.10       now: 1.8.1.2
  # - libcurand=10.3.3.141     now: 10.3.4.101
  - python=3.10.12
  - pytorch=2.0.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0=cuda
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=10.1.243  
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcusolver=11.4.0.1      
  - libcusparse=11.7.4.91
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  #
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=41.0.2
  - ffmpeg=4.3
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openh264=2.1.1
  - openssl=3.0.10
  - pillow=9.4.0
  - pip=23.2.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - cachetools==5.3.1
    - contourpy==1.1.0
    - cycler==0.11.0
    - fonttools==4.42.1
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.57.0
    - h5py==3.9.0
    - imageio==2.31.2
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - markdown==3.4.4
    - matplotlib==3.7.2
    - oauthlib==3.2.2
    - packaging==23.1
    - protobuf==4.24.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.21.0
    - scipy==1.11.2
    - six==1.16.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - tifffile==2023.8.25
    - tqdm==4.66.1
    - werkzeug==2.3.7




