config_name: fastmri_modl,k=1,n=7
description: "\"\""
model_name: base_modl  # base_modl, base_varnet, base_modl_ssdu

k_iters: 1
n_layers: 7

epochs: 100

dataset_name: fastmri_dataset

dataset_params:
  dataset_path: 'data/fastmri_dataset_small.hdf5'
  mask_path: 'data/mask_poisson_accelx8_396_768.mat'
  # mask_path: 'data/trn_loss_mask_ssdu.hdf5'
  sigma: 0.01

val_data: true
batch_size: 1

restore_weights: inter   #False, best, inter, final
restore_path: 'workspace/fastmri_modl,k=1,n=7/checkpoints/'

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: true

# scheduler_name: StepLR
# scheduler_params:
#   step_size: 5
#   gamma: 0.1
