config_name: fastmri_ssdu,k=1,n=7,ispace
description: "\"\""

k_iters: 1
n_layers: 7

epochs: 50

dataset_name: ssdu_fastmri_dataset

dataset_params:
  dataset_path: '../data/fastmri_dataset_small.hdf5'
  mask_path: '../data/trn_loss_mask_ssdu.hdf5'

val_data: true
batch_size: 1
model_name: base_modl_ssdu

restore_weights: False   #False, best, inter, final
restore_path: 'workspace/fastmri_ssdu,k=1,n=1,ispace/checkpoints/'

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: true

# scheduler_name: StepLR
# scheduler_params:
#   step_size: 1
#   gamma: 0.8
